name: ci

on:
  workflow_dispatch: # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      - name: Create 15 days random commits
        run: |
          start_date=$(date -d "-15 days" +%Y-%m-%d)
          for i in $(seq 0 14); do
            random_value=$((RANDOM % 100))
            if [ $random_value -lt 50 ]; then
              num_commits=$(shuf -i 1-2 -n 1) # 浅绿色：每天1到2个提交
            elif [ $random_value -lt 70 ]; then
              num_commits=$(shuf -i 3-4 -n 1) # 稍浅绿色：每天3到4个提交
            elif [ $random_value -lt 85 ]; then
              num_commits=$(shuf -i 5-6 -n 1) # 中等绿色：每天5到6个提交
            elif [ $random_value -lt 95 ]; then
              num_commits=$(shuf -i 7-8 -n 1) # 稍深绿色：每天7到8个提交
            else
              num_commits=$(shuf -i 9-10 -n 1) # 深绿色：每天9到10个提交
            fi
            
            for j in $(seq 1 $num_commits); do
              current_date=$(date -d "$start_date + $i days + $j minutes" +%Y-%m-%dT%H:%M:%S)
              GIT_COMMITTER_DATE="$current_date" GIT_AUTHOR_DATE="$current_date" git commit --allow-empty -m "Empty commit $current_date"
            done
          done

      - name: Push changes
        run: |
          git push origin main
