name: Random Past 15 Days Commits

on:
  workflow_dispatch:

jobs:
  autogreen:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Generate random commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python - <<EOF
          import os
          import random
          from datetime import datetime, timedelta

          # 生成过去15天中的每一天
          days = [datetime.now() - timedelta(days=i) for i in range(15)]

          for day in days:
              # 每天生成0到10个提交
              num_commits = random.randint(0, 10)
              
              for _ in range(num_commits):
                  commit_date = day.strftime('%Y-%m-%dT%H:%M:%S')
                  
                  # 设置Git配置
                  os.system('git config --local user.email "945981976@qq.com"')
                  os.system('git config --local user.name "ZirongLiu"')
                  
                  # 创建一个空提交并设置日期
                  os.system(f'GIT_AUTHOR_DATE="{commit_date}" GIT_COMMITTER_DATE="{commit_date}" git commit --allow-empty -m "update"')

          # 更新远程仓库URL
          os.system('git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}')
          
          # 拉取最新代码并进行rebase
          os.system('git pull --rebase')
          
          # 推送更改到远程仓库
          os.system('git push')
          EOF
