name: ci

on:
  workflow_dispatch: # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # 使用 GitHub 官方的 checkout 操作来检出仓库代码

      - name: Set up Git
        run: |
          git config --global user.name "ZirongLiu" # 配置 Git 用户名
          git config --global user.email "945981976@qq.com" # 配置 Git 用户邮箱

      - name: Create 666 days random commits
        run: |
          start_date=$(date -d "-666 days" +%Y-%m-%d) # 获取666天前的日期，格式为 YYYY-MM-DD
          
          # 循环生成过去666天的每一天
          for i in $(seq 0 665); do
            random_value=$((RANDOM % 100)) # 生成0到99之间的随机数，用于决定当天的提交数量级别
            
            # 根据随机数值决定当天的提交数量级别
            if [ $random_value -lt 50 ]; then
              num_commits=$(shuf -i 1-2 -n 1) # 浅绿色：每天1到2个提交（50%的概率）
            elif [ $random_value -lt 70 ]; then
              num_commits=$(shuf -i 3-4 -n 1) # 稍浅绿色：每天3到4个提交（20%的概率）
            elif [ $random_value -lt 85 ]; then
              num_commits=$(shuf -i 5-6 -n 1) # 中等绿色：每天5到6个提交（15%的概率）
            elif [ $random_value -lt 95 ]; then
              num_commits=$(shuf -i 7-8 -n 1) # 稍深绿色：每天7到8个提交（10%的概率）
            else
              num_commits=$(shuf -i 9-10 -n 1) # 深绿色：每天9到10个提交（5%的概率）
            fi
            
            # 在决定好的数量级别范围内生成提交
            for j in $(seq 1 $num_commits); do
              # 计算当前提交的日期时间，确保提交时间分散在当天不同的分钟
              current_date=$(date -d "$start_date + $i days + $j minutes" +%Y-%m-%dT%H:%M:%S)
              # 设置提交的日期和时间，并生成空提交
              GIT_COMMITTER_DATE="$current_date" GIT_AUTHOR_DATE="$current_date" git commit --allow-empty -m "Empty commit $current_date"
            done
          done

      - name: Push changes
        run: |
          git push origin main # 将生成的提交推送到远程仓库的 main 分支
